name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repo
      - uses: actions/checkout@v3

      # 2. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # 3. Cache de dependencias Maven (acelera el build)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 4. Ejecutar análisis SonarCloud
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar \
          -Dsonar.projectKey=danielariza1_Cafeteria \
          -Dsonar.organization=danielariza1 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
